### ISSUE TITLE
With Yellow 0.7.6 „showstopper“ in line 49

### ISSUE THREAD

**Issue by BsNoSi** [nogginfuel/yellow-plugin-fotorama#2]
With version 0.7.6 the fotorama plugin throws an error. Can be easily fixed be commenting line 49:

``` .php
//		list($width, $height) = $this->yellow->toolbox->detectImageInfo($file->fileName);
```

I didn't investigate this deeply but I could not see a disadvantage or operation error of the plugin (in my usecase).

**Comment by nogginfuel** [comment]
Thanks for alerting me to this issue. I have gone ahead and commented out Line 49 as you suggested. I must admit I've been too busy with other projects to really stay current with all the latest and greatest changes to Yellow.
